# Generated by Django 2.1 on 2018-10-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20181026_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='是否认证'),
        ),
    ]
