# Generated by Django 2.1 on 2018-12-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_teacher_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='course_nums',
        ),
    ]
