# Generated by Django 2.1 on 2019-01-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_courseorg_course_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.CharField(blank=True, default='18', max_length=3, null=True, verbose_name='年龄'),
        ),
    ]
