"""
Django settings for MxOnline project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os
import sys


def add_syspath(apps_path_list):
    for app_path in apps_path_list:
        sys.path.insert(0, app_path)


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APPS_DIR = os.path.join(BASE_DIR, 'apps')
EXTRA_APPS_DIR = os.path.join(BASE_DIR, 'extra_apps')
COURSE_FAV = 1
ORG_FAV = 2
add_syspath([APPS_DIR,
             EXTRA_APPS_DIR
        ])

# 切换环境-  TEST 测试环境  PROD 生产环境
TEST_ENV = True
PROD_ENV = False
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd4y_*olk=&_gaj)pt(5276gj&&+^ascp@^3w65r^-b0h4*lg&%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',# seesion 自动处理的相关程序
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses',
    'organization',
    'operation',
    'xadmin',
    'crispy_forms',
    'captcha',
    'pure_pagination',
    'django_extensions',
]

AUTH_USER_MODEL = "users.UserProfile"
AUTHENTICATION_BACKENDS = [
    'users.views.CustomBackend',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MxOnline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
            'libraries':{
                'useful_tags': 'utils.templatetags.useful_tags',
            },
        },

    },
]

WSGI_APPLICATION = 'MxOnline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
if PROD_ENV:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': "mxonline",
            "USER": "pythonuser",
            "PASSWORD": "WoShiShuaiGe-1",
            "HOST": "209.250.229.232",
        }
    }
elif TEST_ENV:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': "mxonline",
            "USER": "pythonuser",
            "PASSWORD": "test",
            "HOST": "localhost",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 默认存储时间


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
if DEBUG == True:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]

DOMAIN_URL = 'http://127.0.0.1:8000'
EMAIL_HOST = 'smtp.sina.com'
EMAIL_PORT = 25
EMAIL_FROM = EMAIL_HOST_USER = 'fsdeep@sina.com'
EMAIL_HOST_PASSWORD = 'WoShiShuaiGe-1'
ENAIL_USE_TLS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 4,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

CONFIG_ROOT = os.path.join(BASE_DIR, 'utils')
VIDEO_MANAGER = 'aliyun_oss'

FAV_TYPE = {'course': 1,
            'teacher': 3,
            'corg': 2}

