# Generated by Django 2.1 on 2019-02-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20181102_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='message',
            new_name='msg_body',
        ),
    ]
