# Generated by Django 2.1 on 2018-12-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20181219_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructions',
            new_name='instruction',
        ),
    ]
