# Generated by Django 2.1 on 2019-01-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='announcement',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='课程公告；‘ ’'),
        ),
    ]
