# Generated by Django 2.1 on 2019-02-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190106_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否轮播'),
        ),
    ]
