# Generated by Django 2.1.5 on 2019-02-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='announcement',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='课程公告'),
        ),
    ]
