# Generated by Django 2.1 on 2018-08-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='PageBanner',
        ),
    ]
