# Generated by Django 2.1 on 2018-10-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverifyrecord_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='send_status',
            field=models.CharField(choices=[('succeed', '成功'), ('failed', '失败'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='发送状态'),
        ),
    ]
