# Generated by Django 2.1 on 2019-02-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190123_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='valid',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='有效'),
        ),
    ]
